import {
  PAPERWORDS_CACHE_PREFIX,
  getPaperWordsCacheNames,
  type PaperWordsPwaVersions
} from "./version";

export const PAPERWORDS_SW_PATH = "/sw.js";
export const PAPERWORDS_MANIFEST_PATH = "/manifest.webmanifest";

export const PAPERWORDS_PRECACHE_PATHS = [
  "/",
  "/dictionary",
  "/topics",
  "/~offline",
  PAPERWORDS_MANIFEST_PATH,
  "/icons/icon-192.png",
  "/icons/icon-512.png",
  "/icons/maskable-512.png"
] as const;

export const PAPERWORDS_CORE_ASSET_PATHS = new Set<string>([
  PAPERWORDS_MANIFEST_PATH,
  "/icons/icon-192.png",
  "/icons/icon-512.png",
  "/icons/maskable-512.png"
]);

export function generatePaperWordsServiceWorker(versions: PaperWordsPwaVersions): string {
  const cacheNames = getPaperWordsCacheNames(versions);

  return `/* PaperWords service worker. Generated by src/lib/pwa/worker.ts. */
const VERSION = ${JSON.stringify(versions)};
const CACHE_NAMES = ${JSON.stringify(cacheNames)};
const CACHE_PREFIX = ${JSON.stringify(PAPERWORDS_CACHE_PREFIX)};
const PRECACHE_PATHS = ${JSON.stringify(PAPERWORDS_PRECACHE_PATHS)};
const CORE_ASSET_PATHS = new Set(${JSON.stringify([...PAPERWORDS_CORE_ASSET_PATHS])});
const VERSION_SIGNAL = "PAPERWORDS_VERSION";
const CLIENT_MESSAGE_SKIP_WAITING = "SKIP_WAITING";

self.addEventListener("install", (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE_NAMES.precache);
    await cache.addAll(PRECACHE_PATHS);
    await broadcastVersion("installed");
  })());
});

self.addEventListener("activate", (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(
      keys
        .filter((key) => key.startsWith(CACHE_PREFIX + "-") && !Object.values(CACHE_NAMES).includes(key))
        .map((key) => caches.delete(key))
    );
    await self.clients.claim();
    await broadcastVersion("activated");
  })());
});

self.addEventListener("message", (event) => {
  if (event.data && event.data.type === CLIENT_MESSAGE_SKIP_WAITING) {
    self.skipWaiting();
  }
});

self.addEventListener("fetch", (event) => {
  const request = event.request;

  if (!shouldHandleRequest(request)) {
    return;
  }

  const url = new URL(request.url);

  if (request.mode === "navigate") {
    event.respondWith(handleNavigationRequest(request));
    return;
  }

  if (isNextStaticAsset(url) || isCoreAsset(url)) {
    event.respondWith(cacheFirst(request, CACHE_NAMES.static));
  }
});

async function handleNavigationRequest(request) {
  try {
    const response = await fetch(request);
    if (isCacheableNavigationResponse(request, response)) {
      const cache = await caches.open(CACHE_NAMES.pages);
      await cache.put(request, response.clone());
    }
    return response;
  } catch (error) {
    const cached = await caches.match(request);
    if (cached) {
      return cached;
    }

    const url = new URL(request.url);
    if (url.pathname === "/dictionary") {
      const dictionaryShell = await caches.match(new URL("/dictionary", url.origin).toString());
      if (dictionaryShell) {
        return dictionaryShell;
      }
    }

    const offlineFallback = await caches.match(new URL("/~offline", url.origin).toString());
    if (offlineFallback) {
      return offlineFallback;
    }

    return new Response("PaperWords offline fallback is unavailable.", {
      status: 503,
      headers: { "Content-Type": "text/plain; charset=utf-8" }
    });
  }
}

async function cacheFirst(request, cacheName) {
  const cached = await caches.match(request);
  if (cached) {
    return cached;
  }

  const response = await fetch(request);
  if (response.ok) {
    const cache = await caches.open(cacheName);
    await cache.put(request, response.clone());
  }
  return response;
}

function shouldHandleRequest(request) {
  if (request.method !== "GET") {
    return false;
  }

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) {
    return false;
  }

  if (url.pathname === "/sw.js" || url.pathname.startsWith("/api/")) {
    return false;
  }

  if (url.pathname === "/robots.txt" || url.pathname === "/sitemap.xml") {
    return false;
  }

  return true;
}

function isCacheableNavigationResponse(request, response) {
  if (!response || !response.ok || response.type !== "basic") {
    return false;
  }

  return isPublicPagePath(new URL(request.url).pathname);
}

function isPublicPagePath(pathname) {
  return (
    pathname === "/" ||
    pathname === "/dictionary" ||
    pathname === "/topics" ||
    pathname === "/~offline" ||
    pathname.startsWith("/terms/") ||
    pathname.startsWith("/topics/") ||
    pathname.startsWith("/papers/")
  );
}

function isNextStaticAsset(url) {
  return url.pathname.startsWith("/_next/static/");
}

function isCoreAsset(url) {
  return CORE_ASSET_PATHS.has(url.pathname);
}

async function broadcastVersion(lifecycle) {
  const clients = await self.clients.matchAll({ includeUncontrolled: true, type: "window" });
  for (const client of clients) {
    client.postMessage({
      type: VERSION_SIGNAL,
      lifecycle,
      appVersion: VERSION.appVersion,
      contentVersion: VERSION.contentVersion,
      cacheVersion: VERSION.cacheVersion,
      cacheNames: CACHE_NAMES
    });
  }
}
`;
}
